<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Generates the per-client config files and provisioning manifest for an Agency
 * instance clone, replacing the hand-edited `my_config.php` rebrand process with
 * something the provisioning flow can produce programmatically.
 *
 * This library only writes files under upload/agency_instances/{subdomain}/ on the
 * CONTROL PLANE install (the Fluxmuse install selling the Agency package). It does
 * not apply them to a running instance — no clone/deploy automation exists yet, see
 * docs/agency_provisioning.md. A human/automation picks the generated files up from
 * there and seeds the new install's application/config/ with them.
 */
class Agency_branding_generator
{
    protected $CI;
    protected $export_root;

    public function __construct()
    {
        $this->CI =& get_instance();
        $this->export_root = FCPATH . 'upload/agency_instances/';
    }

    /**
     * @param array $instance Row shape matching the `agency_instances` table
     *   (company_name, subdomain, custom_domain, domain_mode, admin_name,
     *   admin_email, product_name, primary_color, logo_path, license_key,
     *   suggested_db_name).
     * @param array $provisioning_config Row from `agency_provisioning_config`.
     * @return string Path (relative to FCPATH) the files were written under.
     */
    public function generate($instance, $provisioning_config)
    {
        $slug = $this->_safe_slug($instance['subdomain']);
        $instance_dir = $this->export_root . $slug . '/';
        $config_dir = $instance_dir . 'config/';

        if (!is_dir($config_dir)) {
            mkdir($config_dir, 0755, true);
        }

        $host = $instance['domain_mode'] === 'custom_domain' && $instance['custom_domain'] !== ''
            ? $instance['custom_domain']
            : $slug . '.' . $provisioning_config['base_domain'];

        file_put_contents($config_dir . 'my_config.php', $this->_render_my_config($instance));
        file_put_contents($config_dir . 'frontend_config.php', $this->_render_frontend_config($instance));
        file_put_contents($instance_dir . 'manifest.json', $this->_render_manifest($instance, $provisioning_config, $host));

        return 'upload/agency_instances/' . $slug . '/';
    }

    protected function _render_my_config($instance)
    {
        $product_name = addslashes($instance['product_name']);
        $company_name = addslashes($instance['company_name']);

        return <<<PHP
<?php
// Generated by Agency_branding_generator for instance "{$instance['subdomain']}".
// Copy this over application/config/my_config.php on the client's clone.
\$config['default_page_url'] = 'page/blank';
\$config['product_name'] = '{$product_name}';
\$config['product_short_name'] = '{$product_name}';
\$config['product_version'] = '9.4.3';
\$config['slogan'] = 'Powered by {$company_name}';

\$config['institute_address1'] = '';
\$config['institute_address2'] = '';
\$config['institute_email'] = '{$instance['admin_email']}';
\$config['institute_mobile'] = '';

\$config['time_zone'] = 'Europe/Dublin';
\$config['language'] = 'english';
PHP;
    }

    protected function _render_frontend_config($instance)
    {
        $primary_color = addslashes($instance['primary_color']);
        $logo_path = addslashes($instance['logo_path']);

        return <<<PHP
<?php
// Generated by Agency_branding_generator for instance "{$instance['subdomain']}".
// Copy this over application/config/frontend_config.php on the client's clone.
\$config['theme_front'] = 'purple';
\$config['display_landing_page'] = '1';
\$config['agency_primary_color'] = '{$primary_color}';
\$config['agency_logo_path'] = '{$logo_path}';
PHP;
    }

    protected function _render_manifest($instance, $provisioning_config, $host)
    {
        $manifest = array(
            'subdomain' => $instance['subdomain'],
            'host' => $host,
            'domain_mode' => $instance['domain_mode'],
            'license_key' => $instance['license_key'],
            'suggested_db_name' => $instance['suggested_db_name'],
            'admin' => array(
                'name' => $instance['admin_name'],
                'email' => $instance['admin_email'],
                'user_type' => 'Admin',
            ),
            'dns' => array(
                'provider' => $provisioning_config['dns_provider'],
                'record_type' => $instance['domain_mode'] === 'custom_domain' ? 'CNAME' : 'A/CNAME',
                'record_name' => $instance['domain_mode'] === 'custom_domain' ? $instance['custom_domain'] : $instance['subdomain'],
                'target' => $instance['domain_mode'] === 'custom_domain'
                    ? $provisioning_config['base_domain']
                    : 'wildcard *.' . $provisioning_config['base_domain'] . ' zone apex',
            ),
            'tls' => array(
                'method' => 'acme_http01_or_dns01',
                'acme_email' => $provisioning_config['acme_email'],
            ),
            'hosting' => array(
                'provider' => $provisioning_config['hosting_provider'],
                'action_needed' => 'clone app codebase + fresh MySQL database named per suggested_db_name, seed with assets/backup_db/initial_db.sql, overlay generated config/ files from this export, run license activation for license_key',
            ),
            'generated_at' => date('c'),
        );

        return json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    protected function _safe_slug($subdomain)
    {
        $slug = strtolower(preg_replace('/[^a-z0-9\-]/i', '', $subdomain));
        return $slug !== '' ? $slug : 'instance-' . time();
    }
}
